version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: ./env/mysql.env

  mysql-exporter:
    image: prom/mysqld-exporter
    env_file: ./env/mysql-exporter.env
    links:
           - "mysql:hello"
    depends_on:
            - mysql
    ports:
            - "9104:9104"

  rabbitmq:
    image: rabbitmq:alpine

  app-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    env_file: ./env/python.env

  app-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: app-node
    depends_on:
      - rabbitmq
      - mysql
    env_file: ./env/node.env