scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: grafana
  scrape_interval: 5s
  static_configs:
  - targets: [ 'grafana:3000' ]

- job_name: node-server
  scrape_interval: 5s
  static_configs:
  - targets: ['node-exporter:9100', 'cadvisor:8080']

- job_name: node-client1
  scrape_interval: 5s
  static_configs:
  - targets: ['10.128.0.27:9100', '10.128.0.27:8080', '10.128.0.27:9104' ]
