scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: cadivisor
  scrape_interval: 5s
  static_configs:
  - targets: [ 'cadvisor:8080' ]

- job_name: node-server
  scrape_interval: 5s
  static_configs:
          - targets: ['node-exporter:9100']

- job_name: node-client1
  scrape_interval: 5s
  static_configs:
          - targets: ['10.128.15.200:9100', '10.128.15.200:8080' ]